services:
  postgres:
    image: postgres:16
    container_name: postgres
    networks:
      - dev-env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    labels:
      - dev.orbstack.domains=postgres.expecto.local

networks:
  dev-env:
    driver: bridge

volumes:
  postgres_data:
    external: true
