name: Bundle Zip Dev Environment Cookiecutter Template

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  bundle-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bundle Zip
        run: |
          zip -r dev-environment-${{ github.ref_name }}.zip . -x .gitignore .github/workflows/bundle-zip.yml
      - name: Upload Release Assets
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v1
        with:
          files: 'dev-environment-${{ github.ref_name }}.zip'
          