name: Bundle Zip Dev Environment Cookiecutter Template

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  bundle-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bundle Zip
        run: |
          zip -r dev-environment-${{ github.ref_name }}.zip . -x .gitignore .github/workflows/bundle-zip.yml
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'dev-environment-${{ github.ref_name }}.zip'
          body: |
            This is the dev environment for the ${{ github.repository }} project. 
            The zip file is named dev-environment-${{ github.ref_name }}.zip.

          