name: Bundle Zip Dev Environment Cookiecutter Template

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  bundle-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bundle Zip
        run: |
          zip -r dev-environment.zip . -x .gitignore .github/workflows/bundle-zip.yml
      - name: Upload Bundle Zip
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: dev-environment.zip
          path: dev-environment.zip

  add-to-release:
    needs: bundle-zip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: dev-environment.zip
          path: dev-environment.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Assets
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v1
        with:
          files: '*.zip'
          body: |
            This is the dev environment for the ${{ github.repository }} project.

      - name: Upload Artifacts
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4
        with:
          path: '*.zip'
      - name: Create Release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/create-release@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
